/* golobal console,window,document ,*/
var Box1 = document.getElementById("box1"),
	Box2 = document.getElementById("box2"),
	Box3 = document.getElementById("box3"),
	Box4 = document.getElementById("box4"),
	Box5 = document.getElementById("box5"),
	Box6 = document.getElementById("box6"),
	Box7 = document.getElementById("box7"),
	Box8 = document.getElementById("box8"),
	Box9 = document.getElementById("box9"),
	Box10 = document.getElementById("box10"),
	Box11 = document.getElementById("box11"),
	Box12 = document.getElementById("box12"),
	Box13 = document.getElementById("box13"),
	Box14 = document.getElementById("box14"),
	Box15 = document.getElementById("box15"),
	Box16 = document.getElementById("box16"),
	msgWin = document.getElementById("win"),
	msgLoss = document.getElementById("loss"),
	myCountDiv = document.getElementById("countdown"),
	myFirstIntervl,mySecondIntervl,
	c=0;
$(document).ready(function(){
	
		setTimeout(function(){
		
		"use strict";
		document.getElementById("lab1").style.display = "block";
//		document.getElementById("lab2").style.display = "block";
		$("#lab2").fadeIn(1000);
		
	},3000);
	
});

Box1.onclick = function(){
	"use strict";
	this.classList.add("Add1");
	this.classList.add("test");
	this.classList.remove("box");
	
	if(Box3.classList.contains("test") && Box3.classList.contains("Add1"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box3.classList.remove("test");
			Box3.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
		
};
Box2.onclick = function(){
	"use strict";
	this.classList.add("Add2");
	this.classList.add("test");
	this.classList.remove("box");

	
	if(Box4.classList.contains("test") && Box4.classList.contains("Add2"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box4.classList.remove("test");
			Box4.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add1");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
};
Box3.onclick = function(){
	"use strict";
	this.classList.add("Add1");
	this.classList.add("test");
	this.classList.remove("box");

	
	if(Box1.classList.contains("test") && Box1.classList.contains("Add1"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box1.classList.remove("test");
			Box1.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add1");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
};
Box4.onclick = function(){
	"use strict";
	this.classList.add("Add2");
	this.classList.add("test");
	this.classList.remove("box");
	
	if(Box2.classList.contains("test") && Box2.classList.contains("Add2"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box2.classList.remove("test");
			Box2.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add2");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
};
Box5.onclick = function(){
	"use strict";
	this.classList.add("Add3");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box12.classList.contains("test") && Box12.classList.contains("Add3"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box12.classList.remove("test");
			Box12.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};

Box6.onclick = function(){
	"use strict";
	this.classList.add("Add4");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box13.classList.contains("test") && Box13.classList.contains("Add4"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box13.classList.remove("test");
			Box13.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};

Box7.onclick = function(){
	"use strict";
	this.classList.add("Add5");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box15.classList.contains("test") && Box15.classList.contains("Add5"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box15.classList.remove("test");
			Box15.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("tes4");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};
Box8.onclick = function(){
	"use strict";
	this.classList.add("Add6");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box9.classList.contains("test") && Box9.classList.contains("Add6"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box9.classList.remove("test");
			Box9.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};
Box9.onclick = function(){
	"use strict";
	this.classList.add("Add6");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box8.classList.contains("test") && Box8.classList.contains("Add6"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box8.classList.remove("test");
			Box8.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add6");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};
Box10.onclick = function(){
	"use strict";
	this.classList.add("Add7");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box16.classList.contains("test") && Box16.classList.contains("Add7"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box16.classList.remove("test");
			Box16.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	
	
};
Box11.onclick = function(){
	"use strict";
	this.classList.add("Add8");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box14.classList.contains("test") && Box14.classList.contains("Add8"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box14.classList.remove("test");
			Box14.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
	
	
};
Box12.onclick = function(){
	"use strict";
	this.classList.add("Add3");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box5.classList.contains("test") && Box5.classList.contains("Add3"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box5.classList.remove("test");
			Box5.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add3");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};

Box13.onclick = function(){
	"use strict";
	this.classList.add("Add4");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box6.classList.contains("test") && Box6.classList.contains("Add4"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box6.classList.remove("test");
			Box6.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add4");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
};

Box14.onclick = function(){
	"use strict";
	this.classList.add("Add8");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box11.classList.contains("test") && Box11.classList.contains("Add8"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box11.classList.remove("test");
			Box11.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add8");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};
Box15.onclick = function(){
	"use strict";
	this.classList.add("Add5");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box7.classList.contains("test") && Box7.classList.contains("Add5"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box7.classList.remove("test");
			Box7.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box10.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box10.classList.add("box");
			Box10.classList.remove("test");
			Box10.classList.remove("Add7");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	if(Box16.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add5");
			this.classList.add("box");
			Box16.classList.add("box");
			Box16.classList.remove("test");
			Box16.classList.remove("Add7");
		}
	
	
};
Box16.onclick = function(){
	"use strict";
	this.classList.add("Add7");
	this.classList.add("test");
	this.classList.remove("box");

	if(Box10.classList.contains("test") && Box10.classList.contains("Add7"))
		{
			this.classList.remove("test");
			this.classList.add("remouve");
			Box10.classList.remove("test");
			Box10.classList.add("remouve");
		}
	//condition To win
	if(Box1.classList.contains("remouve")&&Box2.classList.contains("remouve")&&Box5.classList.contains("remouve")&&Box6.classList.contains("remouve")&&Box7.classList.contains("remouve")&&Box8.classList.contains("remouve")&&Box10.classList.contains("remouve")&&Box11.classList.contains("remouve"))
	{
		msgWin.style.visibility="visible";
		$("#restart").fadeIn();
		window.clearInterval(myFirstIntervl);
	}
	
	//
	if(Box2.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box2.classList.add("box");
			Box2.classList.remove("test");
			Box2.classList.remove("Add2");
		}
	if(Box4.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box4.classList.add("box");
			Box4.classList.remove("test");
			Box4.classList.remove("Add2");
		}
	if(Box5.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box5.classList.add("box");
			Box5.classList.remove("test");
			Box5.classList.remove("Add3");
		}
	if(Box6.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box6.classList.add("box");
			Box6.classList.remove("test");
			Box6.classList.remove("Add4");
		}
	if(Box7.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box7.classList.add("box");
			Box7.classList.remove("test");
			Box7.classList.remove("Add5");
		}
	if(Box1.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box1.classList.add("box");
			Box1.classList.remove("test");
			Box1.classList.remove("Add1");
		}
	if(Box9.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box9.classList.add("box");
			Box9.classList.remove("test");
			Box9.classList.remove("Add6");
		}
	if(Box8.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box8.classList.add("box");
			Box8.classList.remove("test");
			Box8.classList.remove("Add6");
		}
	if(Box11.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box11.classList.add("box");
			Box11.classList.remove("test");
			Box11.classList.remove("Add8");
		}
	if(Box12.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box12.classList.add("box");
			Box12.classList.remove("test");
			Box12.classList.remove("Add3");
		}
	if(Box13.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box13.classList.add("box");
			Box13.classList.remove("test");
			Box13.classList.remove("Add4");
		}
	if(Box14.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box14.classList.add("box");
			Box14.classList.remove("test");
			Box14.classList.remove("Add8");
		}
	if(Box15.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box15.classList.add("box");
			Box15.classList.remove("test");
			Box15.classList.remove("Add5");
		}
	if(Box3.classList.contains("test"))
		{
			this.classList.remove("test");
			this.classList.remove("Add7");
			this.classList.add("box");
			Box3.classList.add("box");
			Box3.classList.remove("test");
			Box3.classList.remove("Add1");
		}
	
};
//myFirstIntervl = window.setInterval(function(){
//	"use strict";
//	myCountDiv.textContent = myCountDiv.textContent - 1;
//	if(myCountDiv.textContent < 10)
//		{
//			myCountDiv.textContent = "0" + myCountDiv.textContent;
//			myCountDiv.style.color = "#F00";
//		}
//	if(myCountDiv.textContent == 0)
//		{
//			myCountDiv.textContent = "Done!!"
//			msgLoss.style.visibility = "visible";
//			$("#restart").fadeIn();
//			window.clearInterval(myFirstIntervl);
//			
//		}
//},1000);

$("#restart").click(function(){
	
	$(this).fadeOut();
	msgLoss.style.visibility = "hidden";
	msgWin.style.visibility = "hidden";
	$(".container").children().removeClass("remouve Add1 Add2 Add3 Add4 Add5 Add6 Add7 Add8");
	$(".container").children().addClass("box");
	
	myCountDiv.textContent = "30";
	
	myFirstIntervl = window.setInterval(function(){
	"use strict";
	myCountDiv.textContent = myCountDiv.textContent - 1;
	if(myCountDiv.textContent < 10)
		{
			myCountDiv.textContent = "0" + myCountDiv.textContent;
			myCountDiv.style.color = "#F00";
		}
	if(myCountDiv.textContent == 0)
		{
			myCountDiv.textContent = "Done!!"
			msgLoss.style.visibility = "visible";
			$("#restart").fadeIn();
			window.clearInterval(myFirstIntervl);
		}
			if(myCountDiv.textContent >= 10)
		{
			myCountDiv.style.color = "#FFF";
		}			
},1000);
	
});

$("#StartGame").on('click',function(){
	
	$(this).parent().css("visibility","hidden");
	$(".boss").css("visibility","visible");
	$("#restart").css("visibility","hidden");
	msgLoss.style.visibility = "hidden";
	msgWin.style.visibility = "hidden";
	myCountDiv.textContent = "30";
	
	mySecondIntervl = window.setInterval(function(){
	"use strict";
	myCountDiv.textContent = myCountDiv.textContent - 1;
	if(myCountDiv.textContent < 10)
		{
			myCountDiv.textContent = "0" + myCountDiv.textContent;
			myCountDiv.style.color = "#F00";
		}
	if(myCountDiv.textContent == 0)
		{
			myCountDiv.textContent = "Done!!"
			msgLoss.style.visibility = "visible";
			$("#restart").css("visibility","visible");
			window.clearInterval(mySecondIntervl);
			
		}
},1000);

	
//	window.setInterval(function(){
//		"use strict";
//		myCountDiv.textContent = myCountDiv.textContent - 1;
//	if(myCountDiv.textContent < 10)
//		{
//			myCountDiv.textContent = "0" + myCountDiv.textContent;
//			myCountDiv.style.color = "#F00";
//		}
//	if(myCountDiv.textContent == 0)
//		{
//			myCountDiv.textContent = "Done!!"
//			msgLoss.style.visibility = "visible";
//			$("#restart").fadeIn();
//			window.clearInterval(myFirstIntervl);
//		}
//			if(myCountDiv.textContent >= 10)
//		{
//			myCountDiv.style.color = "#FFF";
//		}			
//		
//	},1000)
});

$("#return").click(function(){
	
	$(this).parent().css("visibility","hidden");
	$("#choice").css("visibility","visible");
	
});

	$("#lab2").click(function(){
		
		$(this).parent().css("visibility","hidden");
	});